### ISSUE TITLE
UI freezes when computing pushouts

### ISSUE THREAD

**Issue by ComFreek** [UFrameIT/UFrameIT#12]
When I press the *magic* button, the UI freezes until MMT responds (as visible in the MMT console window). Do we do the network requests synchronously in the main thread?

**Comment by richardmarcus** [comment]
probably should implement this correctly once #17 is closed

**Comment by ComFreek** [comment]
I haven't heard/seen this issue in recent times. This ticket might be stale, closing. Feel free to reopen.
