### ISSUE TITLE
Make a dmg for MacOS

### ISSUE THREAD

**Issue by kohlhase** [UFrameIT/UFrameIT#51]
It is good to have UFrameIT as an app. But for Mac deployment a DMG file is standard, and that is easy to do: see e.g. https://desi-jarvis.medium.com/converting-an-app-file-to-dmg-on-macos-1027422f5efb (at the bottom). 
And then we can put a README and a Drag-to-applications image in there as well. This should be easy to integrate into the creation script via https://www.recitalsoftware.com/blogs/148-howto-build-a-dmg-file-from-the-command-line-on-mac-os-x

**Comment by ComFreek** [comment]
When done, we should document creation of the DMG in [DEPLOY.md](https://github.com/UFrameIT/UFrameIT/blob/master/DEPLOY.md#deploying-binaries-for-uframeit)

**Comment by kohlhase** [comment]
Oh, and the app should probably be called FrameWorld, not...
<img width="124" alt="Screenshot 2021-01-20 at 08 10 33" src="https://user-images.githubusercontent.com/4037538/105139805-12935700-5af7-11eb-9bf3-db7e26cae6ed.png">

**Comment by kohlhase** [comment]
thanks for the good work. But this is not quite how it should be. 
* the *.dmg should not be compressed (indeed the compression saves less than 5% if I see correctly). 
* there should at least be a readme that has the instructions on the releases page
* The name of the should not be `FrameWorld.app`, but just `FrameWorld`.
