### ISSUE TITLE
Unable to push master to https://gl.kwarc.info/FrameIT/uframeit

### ISSUE THREAD

**Issue by fastrich** [UFrameIT/UFrameIT#72]
Want to push master from exisiting https://github.com/UFrameIT/UFrameIT 
to the main branch on the new Gitlab https://gl.kwarc.info/FrameIT/uframeit
without loosing the old Git-relevant datas and references.

Context to https://github.com/UFrameIT/UFrameIT:
- This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

To upload it despite not having some deprecated Files, i changed the GitConfig with "git config lfs.allowincompletepush true"
        - git lfs push --all gl_origin main --> finishes
	- git push -uf gl_origin main --> still "remote rejected" because lfs missing.

**Comment by MaZiFAU** [comment]
Is this still relevant?

**Comment by fastrich** [comment]
Thanks for the reminder. The situation was solved, by buying additional bandwidth for the transfer.
